app:
  host: "localhost"
  port: 8000
  path: "ttl"
  version: "1.1.0"
  logLevel: "ERROR"

database:
  driverName: "postgresql"
  username: "postgres"
  password: "test"
  host: "localhost"
  port: 5432
  name: "TODO"
