app:
  name: "TTL"
  port: 8000
  version: "1.1.0"
  logLevel: "ERROR"

database:
  name: "TODO"
  driverName: "postgresql"
  username: "postgres"
  password: "test"
  host: "localhost"
  port: 5432
  logLevel: "ERROR"
